### PR TITLE
Add controller to create & reconcile cluster claims

### PR DESCRIPTION
**Pull request by elgnay**
Signed-off-by: Yang Le <yangle@redhat.com>

The task link: https://github.com/open-cluster-management/backlog/issues/7157

### CODE REVIEW

**Comment by elgnay** [comment]
The e2e test can not pass until https://github.com/open-cluster-management/registration-operator/pull/96 is merged, because the ClusterClaim crd is not available yet.

**Review by qiujian16 — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
