### PR TITLE
change rest mapper

### PR DESCRIPTION
**Pull request by ldpliu**
https://github.com/open-cluster-management/backlog/issues/12776

### CODE REVIEW

**Comment by ldpliu** [comment]
@anthonyfister With this fix, we can reduce many api calls and could have a more consolidated fix for https://github.com/open-cluster-management/backlog/issues/12776. so it's better to merge this pr to 2.2.5.

**Comment by qiujian16** [comment]
/hold
/approve
/lgtm

unhold this when we agree on that this should be backported in 2.2.5

**Pull request merged**
